@c  This file includes everything after the titlepage.


@ifnothtml
@c @shortcontents  @c (if the table of content gets too large.)
@contents
@end ifnothtml


@menu
* Overview::                                Brief overview of @command{sat}.
* Invoking::                                Invocation of @command{sat}.
* Hooks::                                   How to use hooks.
* Output::                                  How the output is formatted.

* Free Software Needs Free Documentation::  Why free documentation is important.
* GNU Free Documentation License::          Copying and sharing this manual.
@end menu
@c In GNU Emacs a @detailmenu can be created with `C-c C-u m`.


@include chap/overview.texinfo
@include chap/invoking.texinfo
@include chap/hooks.texinfo
@include chap/output.texinfo

@include appx/free-software-needs-free-documentation.texinfo

@node GNU Free Documentation License
@appendix GNU Free Documentation License
@include appx/fdl.texinfo

